services:
  _defaults:
    autowire: false
    autoconfigure: false

  discounter.infrastructure.repository.customer.dbal:
    class: Discounter\Infrastructure\Repository\Customer\DbalRepository
    arguments:
      - '@doctrine.dbal.default_connection'

  discounter.infrastructure.repository.category.dbal:
    class: Discounter\Infrastructure\Repository\Category\DbalRepository
    arguments:
      - '@doctrine.dbal.default_connection'

  discounter.infrastructure.repository.product.dbal:
    class: Discounter\Infrastructure\Repository\Product\DbalRepository
    arguments:
      - '@doctrine.dbal.default_connection'
